
export type Language = 'fr' | 'en' | 'ar' | 'zh' | 'es' | 'hi' | 'ja' | 'it' | 'pt';

export const translations: Record<string, any> = {
  fr: {
    header: {
      title: "8 VIEW AI",
      import: "IMPORT",
      export: "Exportation",
      saveComposite: "Planche Studio",
      saveLayers: "ZIP (Vues séparées)",
      save3D: "Modèle 3D",
      renameTitle: "Nom de l'Asset",
      renamePlaceholder: "Nom de l'Asset",
      downloadZip: "Exporter ZIP",
      cancel: "Annuler"
    },
    sidebar: {
      executionList: "Studio Gallery",
      emptyHistory: "Aucun rendu généré",
      legal: "Mentions Légales"
    },
    info: {
      noSelection: "Sélectionnez un Asset pour analyse",
      statusMap: {
        'Complété': 'Studio Ready',
        'En cours': 'Génération AI...',
        'Échoué': 'Erreur Critique',
        'Brouillon': 'En attente'
      },
      format: "Format", engine: "Engine", dimensions: "Resolution", size: "Poids", type: "Type", date: "Date Gen"
    },
    app: {
      singleSource: "Mode Photo Unique",
      quadView: "Assemblage Manuel",
      expertMode: "MODE EXPERT (Multi-Photos)",
      reconstruct3D: "Visionneuse 3D",
      compare: "Comparatif",
      exploreViews: "Explorer les vues",
      compositeSheet: "Planche Composite",
      exit: "Quitter",
      source: "SOURCE",
      studio: "STUDIO AI",
      exportGLB: "Exporter .GLB",
      exportUSDZ: "Exporter .USDZ"
    },
    landing: {
      enter: "ENTRER DANS LE STUDIO",
      apiKeyPlaceholder: "Collez votre clé API Gemini ici...",
      apiKeyLabel: "CLÉ API GEMINI (OPTIONNEL SI CONFIGURÉ)"
    },
    errors: {
      missingApiKey: "Clé API manquante. Veuillez fournir une clé valide.",
      noImageGenerated: "Aucune image générée par le modèle"
    },
    toasts: {
      studioValidated: "Planche Studio validée en couleurs réelles.",
      aiError: "Échec de l'analyse AI",
      generatingComposite: "Génération de l'export composite...",
      compositeDownloaded: "Planche Composite téléchargée.",
      compositeError: "Erreur lors de l'export composite.",
      generatingZip: "Génération du pack ZIP...",
      zipDownloaded: "ZIP téléchargé avec succès.",
      zipError: "Erreur ZIP.",
      matrixError: "Erreur de matrice."
    }
  },
  en: {
    header: {
      title: "8 VIEW AI",
      import: "IMPORT",
      export: "Export",
      saveComposite: "Studio Sheet",
      saveLayers: "ZIP (Separate Views)",
      save3D: "3D Model",
      renameTitle: "Asset Name",
      renamePlaceholder: "Asset Name",
      downloadZip: "Export ZIP",
      cancel: "Cancel"
    },
    sidebar: {
      executionList: "Studio Gallery",
      emptyHistory: "No renders generated",
      legal: "Legal & Privacy"
    },
    info: {
      noSelection: "Select an Asset for analysis",
      statusMap: {
        'Complété': 'Studio Ready',
        'En cours': 'AI Processing...',
        'Échoué': 'Critical Error',
        'Brouillon': 'Draft'
      },
      format: "Format", engine: "Engine", dimensions: "Resolution", size: "Weight", type: "Type", date: "Gen Date"
    },
    app: {
      singleSource: "Single Photo Mode",
      quadView: "Manual Assembly",
      expertMode: "EXPERT MODE (Multi-Photos)",
      reconstruct3D: "3D Viewer",
      compare: "Compare",
      exploreViews: "Explore Views",
      compositeSheet: "Composite Sheet",
      exit: "Exit",
      source: "SOURCE",
      studio: "STUDIO AI",
      exportGLB: "Export .GLB",
      exportUSDZ: "Export .USDZ"
    },
    landing: {
      enter: "ENTER THE STUDIO",
      apiKeyPlaceholder: "Paste your Gemini API key here...",
      apiKeyLabel: "GEMINI API KEY (OPTIONAL IF CONFIGURED)"
    },
    errors: {
      missingApiKey: "Missing API Key. Please provide a valid key.",
      noImageGenerated: "No image generated by the model"
    },
    toasts: {
      studioValidated: "Studio Sheet validated in true colors.",
      aiError: "AI Analysis Failed",
      generatingComposite: "Generating composite export...",
      compositeDownloaded: "Composite Sheet downloaded.",
      compositeError: "Error during composite export.",
      generatingZip: "Generating ZIP pack...",
      zipDownloaded: "ZIP downloaded successfully.",
      zipError: "ZIP Error.",
      matrixError: "Matrix Error."
    }
  },
  es: {
    header: { title: "8 VIEW AI", import: "IMPORTAR", export: "Exportar", saveComposite: "Hoja de Estudio", saveLayers: "ZIP (Vistas separadas)", save3D: "Modelo 3D", renameTitle: "Nombre del Activo", renamePlaceholder: "Nombre del Activo", downloadZip: "Exportar ZIP", cancel: "Cancelar" },
    sidebar: { executionList: "Galería de Estudio", emptyHistory: "No hay renders", legal: "Aviso Legal" },
    info: { noSelection: "Seleccione un activo", statusMap: { 'Complété': 'Listo', 'En cours': 'Procesando AI...', 'Échoué': 'Error Crítico', 'Brouillon': 'Borrador' }, format: "Formato", engine: "Motor", dimensions: "Resolución", size: "Peso", type: "Tipo", date: "Fecha Gen" },
    app: { singleSource: "Modo Foto Única", quadView: "Ensamblaje Manual", expertMode: "MODO EXPERTO", reconstruct3D: "Visor 3D", compare: "Comparar", exploreViews: "Explorar Vistas", compositeSheet: "Hoja Compuesta", exit: "Salir", source: "FUENTE", studio: "ESTUDIO AI", exportGLB: "Exportar .GLB", exportUSDZ: "Exportar .USDZ" },
    landing: { enter: "ENTRAR AL ESTUDIO", apiKeyPlaceholder: "Pega tu clave API de Gemini aquí...", apiKeyLabel: "CLAVE API GEMINI (OPCIONAL SI CONFIGURADO)" },
    errors: { missingApiKey: "Falta la clave API. Proporcione una clave válida.", noImageGenerated: "El modelo no generó ninguna imagen" },
    toasts: { studioValidated: "Hoja de Estudio validada en colores reales.", aiError: "Análisis de IA fallido", generatingComposite: "Generando exportación compuesta...", compositeDownloaded: "Hoja Compuesta descargada.", compositeError: "Error durante la exportación compuesta.", generatingZip: "Generando paquete ZIP...", zipDownloaded: "ZIP descargado con éxito.", zipError: "Error ZIP.", matrixError: "Error de matriz." }
  },
  pt: {
    header: { title: "8 VIEW AI", import: "IMPORTAR", export: "Exportar", saveComposite: "Folha de Estúdio", saveLayers: "ZIP (Vistas separadas)", save3D: "Modelo 3D", renameTitle: "Nome do Ativo", renamePlaceholder: "Nome do Ativo", downloadZip: "Exportar ZIP", cancel: "Cancelar" },
    sidebar: { executionList: "Galeria de Estúdio", emptyHistory: "Nenhum render", legal: "Aviso Legal" },
    info: { noSelection: "Selecione um ativo", statusMap: { 'Complété': 'Pronto', 'En cours': 'Processando AI...', 'Échoué': 'Erro Crítico', 'Brouillon': 'Rascunho' }, format: "Formato", engine: "Motor", dimensions: "Resolução", size: "Peso", type: "Tipo", date: "Data Gen" },
    app: { singleSource: "Modo Foto Única", quadView: "Montagem Manual", expertMode: "MODO ESPECIALISTA", reconstruct3D: "Visualizador 3D", compare: "Comparar", exploreViews: "Explorar Vistas", compositeSheet: "Folha Composta", exit: "Sair", source: "FONTE", studio: "ESTÚDIO AI", exportGLB: "Exportar .GLB", exportUSDZ: "Exportar .USDZ" },
    landing: { enter: "ENTRAR NO ESTÚDIO", apiKeyPlaceholder: "Cole sua chave API do Gemini aqui...", apiKeyLabel: "CHAVE API GEMINI (OPCIONAL SE CONFIGURADO)" },
    errors: { missingApiKey: "Chave API ausente. Forneça uma chave válida.", noImageGenerated: "Nenhuma imagem gerada pelo modelo" },
    toasts: { studioValidated: "Folha de Estúdio validada em cores reais.", aiError: "Falha na análise de IA", generatingComposite: "Gerando exportação composta...", compositeDownloaded: "Folha Composta baixada.", compositeError: "Erro durante a exportação composta.", generatingZip: "Gerando pacote ZIP...", zipDownloaded: "ZIP baixado com sucesso.", zipError: "Erro ZIP.", matrixError: "Erro de matriz." }
  },
  it: {
    header: { title: "8 VIEW AI", import: "IMPORTA", export: "Esporta", saveComposite: "Foglio Studio", saveLayers: "ZIP (Viste separate)", save3D: "Modello 3D", renameTitle: "Nome Asset", renamePlaceholder: "Nome Asset", downloadZip: "Esporta ZIP", cancel: "Annulla" },
    sidebar: { executionList: "Galleria Studio", emptyHistory: "Nessun render", legal: "Note Legali" },
    info: { noSelection: "Seleziona un asset", statusMap: { 'Complété': 'Pronto', 'En cours': 'Elaborazione AI...', 'Échoué': 'Errore Critico', 'Brouillon': 'Bozza' }, format: "Formato", engine: "Motore", dimensions: "Risoluzione", size: "Peso", type: "Tipo", date: "Data Gen" },
    app: { singleSource: "Modalità Foto Singola", quadView: "Assemblaggio Manuale", expertMode: "MODALITÀ ESPERTO", reconstruct3D: "Visore 3D", compare: "Confronta", exploreViews: "Esplora Viste", compositeSheet: "Foglio Composito", exit: "Esci", source: "FONTE", studio: "STUDIO AI", exportGLB: "Esporta .GLB", exportUSDZ: "Esporta .USDZ" },
    landing: { enter: "ENTRA NELLO STUDIO", apiKeyPlaceholder: "Incolla qui la tua chiave API Gemini...", apiKeyLabel: "CHIAVE API GEMINI (OPZIONALE SE CONFIGURATO)" },
    errors: { missingApiKey: "Chiave API mancante. Fornisci una chiave valida.", noImageGenerated: "Nessuna immagine generata dal modello" },
    toasts: { studioValidated: "Foglio Studio convalidato in colori reali.", aiError: "Analisi AI fallita", generatingComposite: "Generazione esportazione composita...", compositeDownloaded: "Foglio Composito scaricato.", compositeError: "Errore durante l'esportazione composita.", generatingZip: "Generazione pacchetto ZIP...", zipDownloaded: "ZIP scaricato con successo.", zipError: "Errore ZIP.", matrixError: "Errore di matrice." }
  },
  hi: {
    header: { title: "8 VIEW AI", import: "आयात", export: "निर्यात", saveComposite: "स्टूडियो शीट", saveLayers: "ZIP (अलग दृश्य)", save3D: "3D मॉडल", renameTitle: "एसेट का नाम", renamePlaceholder: "एसेट का नाम", downloadZip: "ZIP निर्यात करें", cancel: "रद्द करें" },
    sidebar: { executionList: "स्टूडियो गैलरी", emptyHistory: "कोई रेंडर नहीं", legal: "कानूनी" },
    info: { noSelection: "एक एसेट चुनें", statusMap: { 'Complété': 'तैयार', 'En cours': 'AI प्रोसेसिंग...', 'Échoué': 'गंभीर त्रुटि', 'Brouillon': 'ड्राफ्ट' }, format: "प्रारूप", engine: "इंजन", dimensions: "रिज़ॉल्यूशन", size: "वजन", type: "प्रकार", date: "जनरल तिथि" },
    app: { singleSource: "सिंगल फोटो मोड", quadView: "मैनुअल असेंबली", expertMode: "विशेषज्ञ मोड", reconstruct3D: "3D व्यूअर", compare: "तुलना करें", exploreViews: "दृश्य एक्सप्लोर करें", compositeSheet: "समग्र शीट", exit: "बाहर निकलें", source: "स्रोत", studio: "स्टूडियो AI", exportGLB: ".GLB निर्यात करें", exportUSDZ: ".USDZ निर्यात करें" },
    landing: { enter: "स्टूडियो में प्रवेश करें", apiKeyPlaceholder: "अपनी जेमिनी एपीआई कुंजी यहां पेस्ट करें...", apiKeyLabel: "जेमिनी एपीआई कुंजी (यदि कॉन्फ़िगर किया गया है तो वैकल्पिक)" },
    errors: { missingApiKey: "एपीआई कुंजी गायब है। कृपया एक वैध कुंजी प्रदान करें।", noImageGenerated: "मॉडल द्वारा कोई छवि उत्पन्न नहीं की गई" },
    toasts: { studioValidated: "स्टूडियो शीट को वास्तविक रंगों में मान्य किया गया।", aiError: "AI विश्लेषण विफल", generatingComposite: "समग्र निर्यात उत्पन्न हो रहा है...", compositeDownloaded: "समग्र शीट डाउनलोड की गई।", compositeError: "समग्र निर्यात के दौरान त्रुटि।", generatingZip: "ZIP पैक उत्पन्न हो रहा है...", zipDownloaded: "ZIP सफलतापूर्वक डाउनलोड किया गया।", zipError: "ZIP त्रुटि।", matrixError: "मैट्रिक्स त्रुटि।" }
  },
  ja: {
    header: { title: "8 VIEW AI", import: "インポート", export: "エクスポート", saveComposite: "スタジオシート", saveLayers: "ZIP（個別ビュー）", save3D: "3Dモデル", renameTitle: "アセット名", renamePlaceholder: "アセット名", downloadZip: "ZIPをエクスポート", cancel: "キャンセル" },
    sidebar: { executionList: "スタジオギャラリー", emptyHistory: "レンダリングなし", legal: "法的情報" },
    info: { noSelection: "アセットを選択", statusMap: { 'Complété': '準備完了', 'En cours': 'AI処理中...', 'Échoué': '致命的なエラー', 'Brouillon': '下書き' }, format: "フォーマット", engine: "エンジン", dimensions: "解像度", size: "サイズ", type: "タイプ", date: "生成日" },
    app: { singleSource: "単一写真モード", quadView: "手動アセンブリ", expertMode: "エキスパートモード", reconstruct3D: "3Dビューア", compare: "比較", exploreViews: "ビューを探索", compositeSheet: "コンポジットシート", exit: "終了", source: "ソース", studio: "スタジオAI", exportGLB: ".GLBをエクスポート", exportUSDZ: ".USDZをエクスポート" },
    landing: { enter: "スタジオに入る", apiKeyPlaceholder: "ここにGemini APIキーを貼り付けてください...", apiKeyLabel: "GEMINI APIキー（設定済みの場合は任意）" },
    errors: { missingApiKey: "APIキーがありません。有効なキーを提供してください。", noImageGenerated: "モデルによって画像が生成されませんでした" },
    toasts: { studioValidated: "スタジオシートが実際の色で検証されました。", aiError: "AI分析に失敗しました", generatingComposite: "コンポジットエクスポートを生成中...", compositeDownloaded: "コンポジットシートがダウンロードされました。", compositeError: "コンポジットエクスポート中のエラー。", generatingZip: "ZIPパックを生成中...", zipDownloaded: "ZIPが正常にダウンロードされました。", zipError: "ZIPエラー。", matrixError: "マトリックスエラー。" }
  },
  ar: {
    header: { title: "8 VIEW AI", import: "استيراد", export: "تصدير", saveComposite: "ورقة الاستوديو", saveLayers: "ZIP (طرق عرض منفصلة)", save3D: "نموذج 3D", renameTitle: "اسم الأصل", renamePlaceholder: "اسم الأصل", downloadZip: "تصدير ZIP", cancel: "إلغاء" },
    sidebar: { executionList: "معرض الاستوديو", emptyHistory: "لا توجد تصييرات", legal: "قانوني" },
    info: { noSelection: "حدد أصلاً", statusMap: { 'Complété': 'جاهز', 'En cours': 'معالجة الذكاء الاصطناعي...', 'Échoué': 'خطأ فادح', 'Brouillon': 'مسودة' }, format: "التنسيق", engine: "المحرك", dimensions: "الدقة", size: "الوزن", type: "النوع", date: "تاريخ الإنشاء" },
    app: { singleSource: "وضع الصورة الواحدة", quadView: "تجميع يدوي", expertMode: "وضع الخبير", reconstruct3D: "عارض 3D", compare: "مقارنة", exploreViews: "استكشاف العروض", compositeSheet: "ورقة مركبة", exit: "خروج", source: "المصدر", studio: "استوديو الذكاء الاصطناعي", exportGLB: "تصدير .GLB", exportUSDZ: "تصدير .USDZ" },
    landing: { enter: "أدخل الاستوديو", apiKeyPlaceholder: "الصق مفتاح Gemini API الخاص بك هنا...", apiKeyLabel: "مفتاح GEMINI API (اختياري إذا تم تكوينه)" },
    errors: { missingApiKey: "مفتاح API مفقود. يرجى تقديم مفتاح صالح.", noImageGenerated: "لم يتم إنشاء أي صورة بواسطة النموذج" },
    toasts: { studioValidated: "تم التحقق من ورقة الاستوديو بألوان حقيقية.", aiError: "فشل تحليل الذكاء الاصطناعي", generatingComposite: "جارٍ إنشاء تصدير مركب...", compositeDownloaded: "تم تنزيل الورقة المركبة.", compositeError: "خطأ أثناء التصدير المركب.", generatingZip: "جارٍ إنشاء حزمة ZIP...", zipDownloaded: "تم تنزيل ZIP بنجاح.", zipError: "خطأ ZIP.", matrixError: "خطأ في المصفوفة." }
  },
  zh: {
    header: { title: "8 VIEW AI", import: "导入", export: "导出", saveComposite: "工作室表", saveLayers: "ZIP（单独视图）", save3D: "3D模型", renameTitle: "资产名称", renamePlaceholder: "资产名称", downloadZip: "导出ZIP", cancel: "取消" },
    sidebar: { executionList: "工作室画廊", emptyHistory: "没有渲染", legal: "法律信息" },
    info: { noSelection: "选择一个资产", statusMap: { 'Complété': '准备就绪', 'En cours': 'AI处理中...', 'Échoué': '严重错误', 'Brouillon': '草稿' }, format: "格式", engine: "引擎", dimensions: "分辨率", size: "大小", type: "类型", date: "生成日期" },
    app: { singleSource: "单照片模式", quadView: "手动组装", expertMode: "专家模式", reconstruct3D: "3D查看器", compare: "比较", exploreViews: "探索视图", compositeSheet: "复合表", exit: "退出", source: "来源", studio: "AI工作室", exportGLB: "导出.GLB", exportUSDZ: "导出.USDZ" },
    landing: { enter: "进入工作室", apiKeyPlaceholder: "在此处粘贴您的Gemini API密钥...", apiKeyLabel: "GEMINI API密钥（如果已配置则可选）" },
    errors: { missingApiKey: "缺少API密钥。请提供有效的密钥。", noImageGenerated: "模型未生成任何图像" },
    toasts: { studioValidated: "工作室表已在真实颜色中验证。", aiError: "AI分析失败", generatingComposite: "正在生成复合导出...", compositeDownloaded: "复合表已下载。", compositeError: "复合导出期间出错。", generatingZip: "正在生成ZIP包...", zipDownloaded: "ZIP下载成功。", zipError: "ZIP错误。", matrixError: "矩阵错误。" }
  }
};
